# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/gms-mosey/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/gms-mosey/mosey

$(call soong_config_set_bool,gms_mosey,uses_nopauth,$(TARGET_USES_MOSEY_NOPAUTH))

PRODUCT_COPY_FILES += \
    vendor/gms-mosey/mosey/etc/init/mosey.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/mosey.rc \
    vendor/gms-mosey/mosey/etc/sysconfig/initial-package-stopped-states-mosey.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/sysconfig/initial-package-stopped-states-mosey.xml \
    vendor/gms-mosey/mosey/etc/sysconfig/locked-components-mosey.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/sysconfig/locked-components-mosey.xml

PRODUCT_PACKAGES += \
    libmosey_daemon_ffi \
    manifest_mosey.xml \
    mosey_server
